// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteGalleryFileByIdData, DeleteGalleryFileByIdResponses, DeleteGalleryFolderByIdData, DeleteGalleryFolderByIdResponses, GetGalleryData, GetGalleryFileByIdData, GetGalleryFileByIdResponses, GetGalleryFolderByIdData, GetGalleryFolderByIdResponses, GetGalleryResponses, PostGalleryData, PostGalleryFolderByFolderIdFilesData, PostGalleryFolderByFolderIdFilesResponses, PostGalleryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const deleteGalleryFileById = <ThrowOnError extends boolean = false>(options: Options<DeleteGalleryFileByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteGalleryFileByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/gallery/file/{id}',
    ...options
});

export const getGalleryFileById = <ThrowOnError extends boolean = false>(options: Options<GetGalleryFileByIdData, ThrowOnError>) => (options.client ?? client).get<GetGalleryFileByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/gallery/file/{id}',
    ...options
});

export const deleteGalleryFolderById = <ThrowOnError extends boolean = false>(options: Options<DeleteGalleryFolderByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteGalleryFolderByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/gallery/folder/{id}',
    ...options
});

export const getGalleryFolderById = <ThrowOnError extends boolean = false>(options: Options<GetGalleryFolderByIdData, ThrowOnError>) => (options.client ?? client).get<GetGalleryFolderByIdResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/gallery/folder/{id}',
    ...options
});

export const getGallery = <ThrowOnError extends boolean = false>(options?: Options<GetGalleryData, ThrowOnError>) => (options?.client ?? client).get<GetGalleryResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/gallery',
    ...options
});

export const postGallery = <ThrowOnError extends boolean = false>(options?: Options<PostGalleryData, ThrowOnError>) => (options?.client ?? client).post<PostGalleryResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/gallery',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

export const postGalleryFolderByFolderIdFiles = <ThrowOnError extends boolean = false>(options: Options<PostGalleryFolderByFolderIdFilesData, ThrowOnError>) => (options.client ?? client).post<PostGalleryFolderByFolderIdFilesResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ name: 'Authorization', type: 'apiKey' }],
    url: '/gallery/folder/{folderId}/files',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
