// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:32776' | (string & {});
};

export type FileDetailsReadModel = {
    id?: Ulid;
    folderId?: Ulid;
    displayName?: string | null;
    downloadUri?: string | null;
    createdAtUtc?: string;
};

export type FileDetailsResponse = {
    readonly createdAtUtc?: string;
    readonly displayName?: string | null;
    readonly downloadUri?: string | null;
    id?: Ulid;
};

export type FolderDetailsReadModel = {
    displayName?: string | null;
    files?: Array<FileDetailsReadModel> | null;
    createdAtUtc?: string;
    id?: Ulid;
    physicalName?: string | null;
};

export type Ulid = {
    readonly random?: string | null;
    readonly time?: string;
};

export type FileDetailsReadModelWritable = {
    displayName?: string | null;
    downloadUri?: string | null;
    createdAtUtc?: string;
};

export type FileDetailsResponseWritable = {
    [key: string]: never;
};

export type FolderDetailsReadModelWritable = {
    displayName?: string | null;
    files?: Array<FileDetailsReadModelWritable> | null;
    createdAtUtc?: string;
    physicalName?: string | null;
};

export type DeleteGalleryFileByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/file/{id}';
};

export type DeleteGalleryFileByIdResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type DeleteGalleryFileByIdResponse = DeleteGalleryFileByIdResponses[keyof DeleteGalleryFileByIdResponses];

export type GetGalleryFileByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/file/{id}';
};

export type GetGalleryFileByIdResponses = {
    /**
     * OK
     */
    200: FileDetailsResponse;
};

export type GetGalleryFileByIdResponse = GetGalleryFileByIdResponses[keyof GetGalleryFileByIdResponses];

export type DeleteGalleryFolderByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/folder/{id}';
};

export type DeleteGalleryFolderByIdResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type DeleteGalleryFolderByIdResponse = DeleteGalleryFolderByIdResponses[keyof DeleteGalleryFolderByIdResponses];

export type GetGalleryFolderByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/folder/{id}';
};

export type GetGalleryFolderByIdResponses = {
    /**
     * OK
     */
    200: FolderDetailsReadModel;
};

export type GetGalleryFolderByIdResponse = GetGalleryFolderByIdResponses[keyof GetGalleryFolderByIdResponses];

export type GetGalleryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/gallery';
};

export type GetGalleryResponses = {
    /**
     * OK
     */
    200: Array<FolderDetailsReadModel>;
};

export type GetGalleryResponse = GetGalleryResponses[keyof GetGalleryResponses];

export type PostGalleryData = {
    body?: {
        folderDisplayName?: string;
        files?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/gallery';
};

export type PostGalleryResponses = {
    /**
     * OK
     */
    200: Ulid;
};

export type PostGalleryResponse = PostGalleryResponses[keyof PostGalleryResponses];

export type PostGalleryFolderByFolderIdFilesData = {
    body?: {
        files?: Array<Blob | File>;
    };
    path: {
        folderId: Ulid;
    };
    query?: never;
    url: '/gallery/folder/{folderId}/files';
};

export type PostGalleryFolderByFolderIdFilesResponses = {
    /**
     * OK
     */
    200: Ulid;
};

export type PostGalleryFolderByFolderIdFilesResponse = PostGalleryFolderByFolderIdFilesResponses[keyof PostGalleryFolderByFolderIdFilesResponses];
