// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:32776' | (string & {});
};

export type FileDetailsReadModel = {
    id: Ulid;
    folderId: Ulid;
    displayName: string | null;
    downloadUri?: string | null;
    createdAtUtc: string;
};

export type FileDetailsResponse = {
    id?: Ulid;
    displayName?: string | null;
    downloadUri?: string | null;
    createdAtUtc?: string;
};

export type FolderDetailsReadModel = {
    id: Ulid;
    displayName: string | null;
    physicalName: string | null;
    createdAtUtc: string;
    files?: Array<FileDetailsReadModel> | null;
};

export type FolderDetailsReadModelPaginatedResult = {
    items: Array<FolderDetailsReadModel> | null;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    readonly totalPages?: number;
    readonly hasPreviousPage?: boolean;
    readonly hasNextPage?: boolean;
};

export type Ulid = {
    readonly random?: string | null;
    readonly time?: string;
};

export type UpdateFolderDisplayNameRequest = {
    displayName: string;
};

export type FileDetailsReadModelWritable = {
    displayName: string | null;
    downloadUri?: string | null;
    createdAtUtc: string;
};

export type FileDetailsResponseWritable = {
    displayName?: string | null;
    downloadUri?: string | null;
    createdAtUtc?: string;
};

export type FolderDetailsReadModelWritable = {
    displayName: string | null;
    physicalName: string | null;
    createdAtUtc: string;
    files?: Array<FileDetailsReadModelWritable> | null;
};

export type FolderDetailsReadModelPaginatedResultWritable = {
    items: Array<FolderDetailsReadModelWritable> | null;
    totalCount: number;
    pageNumber: number;
    pageSize: number;
};

export type PostGalleryFolderByFolderIdFilesData = {
    body?: {
        files?: Array<Blob | File>;
    };
    path: {
        folderId: Ulid;
    };
    query?: never;
    url: '/gallery/folder/{folderId}/files';
};

export type PostGalleryFolderByFolderIdFilesResponses = {
    /**
     * OK
     */
    200: Ulid;
};

export type PostGalleryFolderByFolderIdFilesResponse = PostGalleryFolderByFolderIdFilesResponses[keyof PostGalleryFolderByFolderIdFilesResponses];

export type GetGalleryData = {
    body?: never;
    path?: never;
    query?: {
        pageNumber?: number;
        pageSize?: number;
    };
    url: '/gallery';
};

export type GetGalleryResponses = {
    /**
     * OK
     */
    200: FolderDetailsReadModelPaginatedResult;
};

export type GetGalleryResponse = GetGalleryResponses[keyof GetGalleryResponses];

export type PostGalleryData = {
    body?: {
        folderDisplayName?: string;
        files?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/gallery';
};

export type PostGalleryResponses = {
    /**
     * OK
     */
    200: Ulid;
};

export type PostGalleryResponse = PostGalleryResponses[keyof PostGalleryResponses];

export type DeleteGalleryFileByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/file/{id}';
};

export type DeleteGalleryFileByIdResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type DeleteGalleryFileByIdResponse = DeleteGalleryFileByIdResponses[keyof DeleteGalleryFileByIdResponses];

export type GetGalleryFileByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/file/{id}';
};

export type GetGalleryFileByIdResponses = {
    /**
     * OK
     */
    200: FileDetailsResponse;
};

export type GetGalleryFileByIdResponse = GetGalleryFileByIdResponses[keyof GetGalleryFileByIdResponses];

export type DeleteGalleryFolderByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/folder/{id}';
};

export type DeleteGalleryFolderByIdResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type DeleteGalleryFolderByIdResponse = DeleteGalleryFolderByIdResponses[keyof DeleteGalleryFolderByIdResponses];

export type GetGalleryFolderByIdData = {
    body?: never;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/folder/{id}';
};

export type GetGalleryFolderByIdResponses = {
    /**
     * OK
     */
    200: FolderDetailsReadModel;
};

export type GetGalleryFolderByIdResponse = GetGalleryFolderByIdResponses[keyof GetGalleryFolderByIdResponses];

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type GetVersionResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type PatchGalleryFolderByIdDisplayNameData = {
    body?: UpdateFolderDisplayNameRequest;
    path: {
        id: Ulid;
    };
    query?: never;
    url: '/gallery/folder/{id}/display-name';
};

export type PatchGalleryFolderByIdDisplayNameResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type PatchGalleryFolderByIdDisplayNameResponse = PatchGalleryFolderByIdDisplayNameResponses[keyof PatchGalleryFolderByIdDisplayNameResponses];
